sudo: false
language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.0
  - android-26
  - extra-android-m2repository
  - extra-google-m2repository
  before script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
addons:
  ssh_known_hosts: aisa.fi.muni.cz
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/rsa_key
#- "./travis-helper.sh"
before_install:
- echo $super_secret_password | gpg --passphrase-fd 0 super_secret.txt.gpg
- chmod +x gradlew
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
script:
- "./gradlew clean build --stacktrace"
notifications:
  email: false
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/public xoravcok@aisa.fi.muni.cz:/home/xoravcok/public_html
  on:
    branch: master
env:
  global:
    secure: LlX+He92rKvzKnJSSUW3UDLqGuh1lWt7px++yyqohqhzLUYoVZPqZml1013t36UAim49Y5yeaxVLHnMivUmg5QsCh/BLiNh9XRWqd0IkofRo7cYl0yV6jLlBtVbH6A/joWiyXajBwuILq7regA+u65sMuzIwVzizi8wSuZb7Z4+6LqS69aq4bABTKogoz2YCZ1B+bbZDZV7ajdjJlfE6qHrye/Bdbv8lrtl1DS1HMuMgsUECeVnemRwvI31jbDUEenM8eXOXwrDK6h19EEAiQxHNQ+l599ieDojQ71IvhK1B52N1A/W1wpCDQZk+bjDWncgkUk7Z2indYvsEAPgV6BE4TPXX2F1hufaD1+6nILfu8qbKHjUjCOd3Nkyp6yvvuSC0DgDKzK7+SmsSosC5dngxDZf9HGwpX/sTm+2CpwhbmbvMjjR6Zzmgu2kGXDOIyMVii7UHPwpCdIlkN1WF5ItxXDde5NjdOg0Zbuiimxxc6eSZEtVL5bMT6YdKqPhY0v/5TjZbzs9g5qPj6R4EYpqK/5RWrrPVn0XYZ35Ot1cCqFi/4tdHcqL0u2Ojo2BwolqhKSWVpYZKS+DTYog3pUnLEncBnIF5z1KWFRdMXYqv3PqHuzZ3CG4sqI+JGziXjaoczHwpkFlYCGFYGMWzGbK4W07QYj3if3JrqHhHTwI=
