sudo: false
language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.3
  - android-24
  - extra-android-m2repository
  - extra-google-m2repository
before_install:
- chmod +x gradlew
script:
- "./gradlew clean build connectedAndroidTest -PdisablePreDex --stacktrace"
notifications:
  email: false
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  api_key:
    secure: EunWgE9XfzUO/4DLqmNLSa0VZYP365AZQFFxxiFOD7hLOAleqk2dlC5IRM3QSudS5RBijAWrrxvJvZZ3zC2762SOPTtmp1k5SvWnrKFNuo0Q/pi73MfQ1NvrKGRuHlbGbDLC9b91Aspr9WPwIVLkW8FNNmvG31vnc6bXf0snwzUCYf8lEln1e7nj540lnfIzy+OTlO7bZx7z6Q7byuYMkBtAiaJoa+0IRqm/KbaQH35Z1uWmF27zcL0p/kb/Hh/yf5Z4D7pQqr+zRPohKsnkOBuTZOg5DspGL1AdpSw7chNvpvZMdJ2mWs8nvlip7jCm1+AVhKOtifJXGzcr79XaHmsPMhRQ9TzMK+z9h+vzJsw0mMsQ3x7NoZ6LDkgOXYxrBFNVy2h2jt6tLHr4QJj2BtRWOejTY1MLOc7yp/9bGK4RiXVpZPno5E7ThPkhijE3OVebwDLpwiQbhogno20BbROzW1xL0Nrlg93mb7JMwmnPa4rNaNUwRmTNMUuIDOY8UDonLrvthG94zoXzhlLRwvukF8gU/E6ZWIVnjF0qCr5c5nTagKnm2CISRf6l+x/a7O/Sv40dbQQBb3wuLLgGpsIS/wxI7Z/vxjclEzOmvHoXFC1JukNAUhhJ3MrDkkyO4OwgbpB6NpzRTc8GDzMirka/XCDwXv+l9pEXjeNY8b0=
  file: app/build/outputs/apk/app-debug.apk
  file_glob: "true"
  skip_cleanup: true
  on:
    branch: master
    repo: piskula/FuelUp
after_success:
  set_tags.sh